#!/bin/bash

#PBS -l ncpus=48
#PBS -l mem=190GB
#PBS -l jobfs=200GB
#PBS -q normal
#PBS -P vp91
#PBS -l walltime=02:00:00
#PBS -l storage=gdata/vp91+scratch/vp91
#PBS -l wd
 
module purge
module load gcc/10.3.0
module load openmpi/4.1.7
module load cuda/12.9.0
module load papi/7.1.0
module load intel-mkl/2024.2.1
module load hpctoolkit/2021.05.15


mpirun -np 1 hpcrun /scratch/vp91/$USER/LULESH/build/hpctoolkit/lulesh2.0 -s 20